# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('text', models.TextField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
